#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

start() {
    php $DIR/../clamp/clamp.php start
}
 
stop() {
    echo -en "\n"
    php $DIR/../clamp/clamp.php stop
    exit $?
}

if [ "$#" == "0" ]; then
    trap stop SIGINT
    start

    while true; do read x; done
else
    php $DIR/../clamp/clamp.php "$@"
fi
