#!/bin/bash

# get the directory this script is in
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

start() {
    php ${DIR}/clamp.php start
}
 
stop() {
    echo -en "\n"
    php ${DIR}/clamp.php stop
    exit $?
}

if [ "$#" == "0" ]; then
    trap stop SIGINT
    start

    while true; do read x; done
else
    php ${DIR}/clamp.php "$@"
fi
