#!/bin/bash

start() {
    php /usr/local/clamp/clamp.php start
}
 
stop() {
    echo -en "\n"
    php /usr/local/clamp/clamp.php stop
    exit $?
}

if [ "$#" == "0" ]; then
    trap stop SIGINT
    start

    while true; do read x; done
else
    php /usr/local/clamp/clamp.php "$@"
fi
